spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SPRING_BATCH?rewriteBatchedStatements=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true
  batch:
    jdbc:
      initialize-schema: never

logging.level:
  org.hibernate.SQL: debug
