spring:
  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema:

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

    show-sql: true
